### ISSUE TITLE
获取添加好友信息列表target为空

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/flutter_imclient#1]
<img width="784" alt="截屏2021-01-30 上午3 17 02" src="https://user-images.githubusercontent.com/6111056/106345985-9d8e0180-62ee-11eb-8052-926f7bf37de9.png">

我用你们的flutter 模块，A给B发送了好友请求，在B这里获取请求，没有获得正确的好友请求列表呢，特别是target为空,而且我接口调用的方向是Receive但是返回的数据是Send

  ///获取某个用户相关的好友请求
  static Future<FriendRequest> getFriendRequest(
      String userId, FriendRequestDirection direction) async {
    Map<dynamic, dynamic> data = await _channel.invokeMethod(
        "getFriendRequest", {"userId": userId, "direction": direction.index});
    return _convertProtoFriendRequest(data);
  }

同时 getIncommingFriendRequest getOutgoingFriendRequest 这两个函数获取到的数据也是空数组

**Comment by heavyrain2012** [comment]
我们在ios手机上测试了一下，是能够获取到的，请确认是不是发送成功了

另外我们提供的demo太简陋了，是不是可以给我们提供一些UI代码，这样后面遇到问题，我们也能更方便的来复现测试

**Comment by dotcool** [comment]
我们也才做一点点哦，等做好了可以共享的哈

**Comment by heavyrain2012** [comment]
你加微信 wildfirechat ，我们微信沟通一下

**Comment by heavyrain2012** [comment]
这个问题解决了吗，如果解决了就关了吧
