### ISSUE TITLE
android推送不行，苹果可以正常推送

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/flutter_imclient#11]
华为手机，消息推送没有到达

**Comment by heavyrain2012** [comment]
需要按照华为推送的文档检查一下，有可能是接口有变化

**Comment by dotcool** [comment]
华为推送改了好多哦，我看你们的配置是2年前的，能否更新一下华为推送吖

**Comment by dotcool** [comment]
我这边在尝试使用android推送

我写死appId
![image](https://user-images.githubusercontent.com/6111056/111254598-5e263500-8650-11eb-9953-72620e00494b.png)
也会出现下边的错误，直接跳出了
![image](https://user-images.githubusercontent.com/6111056/111254574-536ba000-8650-11eb-8492-de7b85471f1a.png)

`GeneratedPluginsRegister: Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@1f2f67b) but could not find and invoke the GeneratedPluginRegistrant.`

华为推送无法使用
