### ISSUE TITLE
同样的代码，android可以拉取正确的数据，但是ios不行

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/flutter_imclient#13]
A和B聊天，A是ios，B是android，fromIndex都是35但是 ios平台返回的数据是24，23，22...这样
`
flutter: fromIndex:35
flutter: _convertProtoMessage：Message{messageId: 24, messageUid: 212181481991208961, conversation: Conversation{conversationType: ConversationType.Single, target: 776090, line: 0}, fromUser: 776090, toUsers: null, content: Instance of 'TextMessageContent', direction: MessageDirection.MessageDirection_Receive, status: MessageStatus.Message_Status_Readed, serverTime: 1615912014896}
flutter: _convertProtoMessage：Message{messageId: 23, messageUid: 212181475043344385, conversation: Conversation{conversationType: ConversationType.Single, target: 776090, line: 0}, fromUser: 776090, toUsers: null, content: Instance of 'TextMessageContent', direction: MessageDirection.MessageDirection_Receive, status: MessageStatus.Message_Status_Readed, serverTime: 1615912011583}
flutter: _convertProtoMessage：Message{messageId: 22, messageUid: 212150135098998785, conversation: Conversation{conversationType: ConversationType.Single, target: 776090, line: 0}, fromUser: 209232, toUsers: null, c
`

android可以返回正确fromIndex的数据
 fromIndex:35
`I/flutter (26182): front:true element:Message{messageId: 34, messageUid: 212197315069378561, conversation: Conversation{conversationType: ConversationType.Single, target: 209232, line: 0}, fromUser: 209232, toUsers: null, content: Instance of 'TextMessageContent', direction: MessageDirection.MessageDirection_Receive, status: MessageStatus.Message_Status_Readed, serverTime: 1615919564696}
I/flutter (26182): front:true element:Message{messageId: 33, messageUid: 212197307125366785, conversation: Conversation{conversationType: ConversationType.Single, target: 209232, line: 0}, fromUser: 776090, toUsers: null, content: Instance of 'TextMessageContent', direction: MessageDirection.MessageDirection_Send, status: MessageStatus.Message_Status_Sent, serverTime: 1615919560908}
I/flutter (26182): front:true element:Message{messageId: 32, messageUid: 212197300181696513, conversation: Conversation{conversationType: ConversationType.Single, target: 209232, line: 0}, fromUser: 209232, toUsers: null, content: Instance of 'TextMessageContent', direction: MessageDirection.MessageDirection_Receive, status: MessageStatus.Message_Status_Readed, serverTime: 1615919557597}
I/flutter (26182): front:true element:Message{messageId: 31, messageUid: 212195500988858369, conversation: Conversation{conversationType: ConversationType.Single, target: 209232, line: 0}, fromUser: 776090, toUsers: null, content: Instance of 'TextMessageContent', direction: MessageDirection.MessageDirection_Send, status: MessageStatus.Message_Status_Sent, serverTime: 1615918699675}
I/flutter (`
麻烦看看哦，同样的代码返回不同数据

**Comment by heavyrain2012** [comment]
调用的是那个接口？

**Comment by dotcool** [comment]
`    var fromIndex = 0;

    if (messages != null && messages.isNotEmpty) {
      fromIndex = messages.last.messageId;
    }

    if (widget.conversationinfo.lastMessage != null) {
      fromIndex = widget.conversationinfo.lastMessage.messageId + 1;
    }
    print("fromIndex:${fromIndex}");
    FlutterImclient.getMessages(widget.conversation, fromIndex, -20)
        .then((value) {
      _appendMessage(value, front: true);
      _isLoadingMore = false;
    });`
代码是这样的哦，调用的getMessages，现在是ios平台有问题，谢谢啦

**Comment by heavyrain2012** [comment]
你微信联系我一下，还是没有看明白问题，微信号 wildfirechat

**Comment by dotcool** [comment]
好的，感谢

**Comment by heavyrain2012** [comment]
现在确实是两个平台不一致，实际上是android平台有问题，已经修正，请参考 https://github.com/wildfirechat/flutter_imclient/commit/304140dd369dab8bbdf1370e1462bc42a60749c2

获取消息方法需要与我们demo保持一致
