### ISSUE TITLE
缺少获取收藏的群聊列表接口

### ISSUE THREAD

**Issue by yohom** [wildfirechat/flutter_imclient#16]
目前有getFavUsers接口来获取收藏的用户，但是没有类似getFavGroups的接口来获取收藏的群聊。

**Comment by heavyrain2012** [comment]
已添加，请参考 https://github.com/wildfirechat/flutter_imclient/commit/b324ebd1c8cc089e868bdf8eed30a0bafdd1da99 https://github.com/wildfirechat/flutter_imclient/commit/d2bf686f333cd158760aedb01558c1f701212f09
