### ISSUE TITLE
createGroup方法错误

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/flutter_imclient#2]
![image](https://user-images.githubusercontent.com/6111056/106346944-87377400-62f5-11eb-85e3-32134cec44b0.png)
android原生代码里面获取的是  int groupType = call.argument("groupType");
但是模块里面传递的是type 
![image](https://user-images.githubusercontent.com/6111056/106346982-d67da480-62f5-11eb-8c3f-aa562c9e4562.png)
这里不对应哦，而且即使我改了也错误
我修改成了
`    Map<String, dynamic> item = await _convertMessageContent(notifyContent);
    await _channel.invokeMethod("createGroup", {
      "requestId": requestId,
      "groupId": groupId,
      "groupName": groupName,
      "groupPortrait": groupPortrait,
      "groupType": type,
      "members": members,
      "notifyLines": notifyLines,
      "notifyContent": item
    });`
提示动态库里面的错误
 java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: java_array == null
java_vm_ext.cc:542]     in call to GetArrayLength
 java_vm_ext.cc:542]     from void com.tencent.mars.proto.ProtoLogic.createGroup(java.lang.String, java.lang.String, java.lang.String, int, java.lang.String[], int[], cn.wildfirechat.model.ProtoMessageContent, com.tencent.mars.proto.ProtoLogic$IGeneralCallback2)

at com.tencent.mars.proto.ProtoLogic.createGroup(Native method)
at cn.wildfirechat.flutter_imclient.FlutterImclientPlugin.onMethodCall(FlutterImclientPlugin.java:748)

**Comment by dotcool** [comment]
![image](https://user-images.githubusercontent.com/6111056/106347924-2f9d0680-62fd-11eb-8865-e8551cc22dc5.png)
还是参数问题 模块中的参数是groupMembers但是dart里面是members 

还有就是dart里面没有long这个文件里的long需要修改这样获取

third/flutter_imclient/android/src/main/java/cn/wildfirechat/flutter_imclient/FlutterImclientPlugin.java
long updateDt = Long.valueOf(call.argument("updateDt").toString());

**Comment by heavyrain2012** [comment]
dart没有long，用int就可以了，另外两个问题已经修改了。

创建群组错误问题，可以试试notifyContent传空试试，如果还是不行，IM服务有个禁止客户端自定义群操作通知的开关关掉就行。

**Comment by dotcool** [comment]
不行的android这边长整是long哦

**Comment by dotcool** [comment]
IM服务有个禁止客户端自定义群操作通知的开关关掉？这个是在哪里配置吖吖

**Comment by dotcool** [comment]
传空也不行的
 Unhandled Exception: NoSuchMethodError: The method 'encode' was called on null.

**Comment by dotcool** [comment]
## 是否允许客户端发送操作群的自定义群通知消息
group.allow_client_custom_operation_notification true

我这样设置的也重启了服务器，还是不行哦，提示248

**Comment by dotcool** [comment]
麻烦帮我看看这个问题哦，卡在创建群这里，群的相关操作都不行了

**Comment by heavyrain2012** [comment]
用我们刚提的代码，别填groupId，notifyLine，notifyContent， 试一下

**Comment by dotcool** [comment]
嗯，可以了。请问现在有没有获取群列表的接口呢，比如我创建的群，我加入的群

**Comment by heavyrain2012** [comment]
没有，跟微信一样，可以收藏，可以查看收藏的群组
