### ISSUE TITLE
集成后打包发布版本，提示错误

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/flutter_imclient#5]
AILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':flutter_imclient:profileRuntimeClasspath'.
   > Could not resolve project :push.
     Required by:
         project :flutter_imclient
      > Unable to find a matching variant of project :push:
          - Variant 'debugApiElements' capability android:push:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'debug'.
                  - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
          - Variant 'debugRuntimeElements' capability android:push:unspecified:
              - Incompatible attribute:

**Comment by heavyrain2012** [comment]
把我们的代码更新到最新，然后插上手机运行一遍，再命令行到 example目录下执行命令: flutter build apk 试一下

**Comment by dotcool** [comment]
可以了，nice，感谢
