### ISSUE TITLE
在群里面发送消息获取不到消息的fromUser

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/flutter_imclient#6]
![image](https://user-images.githubusercontent.com/6111056/106382244-445ec480-63f9-11eb-8169-e77c9243ec78.png)

I/flutter (26354): _convertProtoMessage：Message{messageId: 7, messageUid: 204170120176631809, conversation: Conversation{conversationType: ConversationType.Group, target: gjgGgGLL, line: 0}, fromUser: , toUsers: null, content: Instance of 'TextMessageContent', direction: MessageDirection.MessageDirection_Send, status: MessageStatus.Message_Status_Sent, serverTime: 1612091899895}

**Comment by heavyrain2012** [comment]
已接近，更新到最新试一下

**Comment by dotcool** [comment]
好的
