### ISSUE TITLE
群创建成功了，但是memberCount数据不正确

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/flutter_imclient#7]
![image](https://user-images.githubusercontent.com/6111056/106416919-8e918580-648d-11eb-9403-e97d0e1a9f9f.png)
创建群有1个人在里面，但是memberCount返回的值是0

**Comment by heavyrain2012** [comment]
IM服务的问题，如果创建群时没有把自己加入到群列表中时，会自动把自己加入，但没有计数。可以下载最新代码编译使用，或者创建群组时把自己也加入到群成员列表中
