### ISSUE TITLE
flutter 的videoMessage 的content参数和安卓不一致

### ISSUE THREAD

**Issue by pslxx** [wildfirechat/flutter_imclient#8]
在视频消息里，安卓发送的视频消息 content里 {w:xx,h:xx,d:xx}
但是在flutter里，视频消息的格式是 {duration:xx}

直接导致安卓和flutter互发消息，视频长度相互不能读取到

**Comment by heavyrain2012** [comment]
已经更新android和flutter代码，可以互通了
